---
# tasks file for openvas

- name: add openvas ppa
  apt_repository:
    repo='ppa:mrazavi/openvas'
    update_cache=yes
    state=present

# openvas installation required user promt, and ansible apt module hangs when it's needed
# 'force' option doesn't helps in this way
# also tried to use '-y' option and 'APT:: Get::Assume-Yes "true";' in apt config with no luck
- name: install openvas
  apt:
    name=openvas
    state=present
  environment: 
    DEBIAN_FRONTEND: noninteractive

- name: install nmap
  apt:
    name=nmap
    state=present

- name: update opanvas data
  command: openvas-nvt-sync && openvas-scapdata-sync && openvas-certdata-sync

- name: restart openvas services
  service: name={{ item }} state=restarted
  with_items:
    - openvas-scanner
    - openvas-manager

- name: rebuild openvasmd
  command: openvasmd --rebuild --progress
