---
# tasks file for openvas

- name: add openvas ppa
  apt_repository:
    repo='ppa:mrazavi/openvas'
    update_cache=yes
    state=present

- name: configure openvas-scanner
  debconf:
    name: openvas-scanner
    question: openvas-scanner/enable_redis
    vtype: boolean
    value: true

- name: install openvas
  apt:
    name=openvas
    state=present

- name: install nmap
  apt:
    name=nmap
    state=present

- name: update opanvas data
  command: openvas-nvt-sync && openvas-scapdata-sync && openvas-certdata-sync

- name: restart openvas services
  service: name={{ item }} state=restarted
  with_items:
    - openvas-scanner
    - openvas-manager

- name: rebuild openvasmd
  command: openvasmd --rebuild --progress
